package com.flowforge.enums;

import java.util.HashMap;
import java.util.Map;

public enum Language {
    AFRIKAANS("Afrikaans"),
    ALBANIAN("Albanian"),
    AMHARIC("Amharic"),
    ARABIC("Arabic"),
    ARABIC_EGYPTIAN("Egyptian Arabic"),
    ARMENIAN("Armenian"),
    AZERBAIJANI("Azerbaijani"),
    BALOCHI("Balochi"),
    BASQUE("Basque"),
    BELARUSIAN("Belarusian"),
    BENGALI("Bengali"),
    BHOJPURI("Bhojpuri"),
    BOSNIAN("Bosnian"),
    BRETON("Breton"),
    BULGARIAN("Bulgarian"),
    BURMESE("Burmese"),
    CHEWA("Chewa"),
    CHHATTISGARHI("Chhattisgarhi"),
    CHOPI("Chopi"),
    CROATIAN("Croatian"),
    CZECH("Czech"),
    DANISH("Danish"),
    DHUNDHARI("Dhundhari"),
    DUTCH("Dutch"),
    ENGLISH("English"),
    ESTONIAN("Estonian"),
    FAROESE("Faroese"),
    FARSI("Farsi"),
    FINNISH("Finnish"),
    FRENCH("French"),
    FULA("Fula"),
    GANDA("Ganda"),
    GEORGIAN("Georgian"),
    GERMAN("German"),
    GREEK("Greek"),
    GREENLANDIC("Greenlandic"),
    GUJARATI("Gujarati"),
    HAITIAN_CREOLE("Haitian Creole"),
    HAUSA("Hausa"),
    HERERO("Herero"),
    HILIGAYNON("Hiligaynon"),
    HINDI("Hindi"),
    HMONG("Hmong"),
    HUNGARIAN("Hungarian"),
    ICELANDIC("Icelandic"),
    IGBO("Igbo"),
    ILOCANO("Ilocano"),
    INDONESIAN("Indonesian"),
    IRISH("Irish"),
    ITALIAN("Italian"),
    JAVANESE("Javanese"),
    JAPANESE("Japanese"),
    KABYLE("Kabyle"),
    KANNADA("Kannada"),
    KAZAKH("Kazakh"),
    KIKONGO("Kikongo"),
    KINYARWANDA("Kinyarwanda"),
    KIRUNDI("Kirundi"),
    KONKANI("Konkani"),
    KOREAN("Korean"),
    KURDISH("Kurdish"),
    LATVIAN("Latvian"),
    LINGALA("Lingala"),
    LITHUANIAN("Lithuanian"),
    LUXEMBOURGISH("Luxembourgish"),
    MACEDONIAN("Macedonian"),
    MAITHILI("Maithili"),
    MALAY("Malay"),
    MALAYALAM("Malayalam"),
    MALTESE("Maltese"),
    MANDARIN("Mandarin"),
    MARATHI("Marathi"),
    MONGOLIAN("Mongolian"),
    MOSSI("Mossi"),
    NAMA("Nama"),
    NDEBELE("Ndebele"),
    NEPALI("Nepali"),
    NORWEGIAN("Norwegian"),
    ORIYA("Oriya"),
    OSHIWAMBO("Oshiwambo"),
    PASHTO("Pashto"),
    PERSIAN("Persian"),
    POLISH("Polish"),
    PORTUGUESE("Portuguese"),
    QUECHUA("Quechua"),
    ROMANIAN("Romanian"),
    RONGA("Ronga"),
    RUSSIAN("Russian"),
    SAMI("Sami"),
    SAN("San"),
    SCOTS_GAELIC("Scots Gaelic"),
    SERBIAN("Serbian"),
    SERBO_CROATIAN("Serbo-Croatian"),
    SHONA("Shona"),
    SINHALA("Sinhala"),
    SLOVAK("Slovak"),
    SOMALI("Somali"),
    SONINKE("Soninke"),
    SOTHO("Sotho"),
    SOUTHERN_MIN("Southern Min"),
    SPANISH("Spanish"),
    SUNDANESE("Sundanese"),
    SWAHILI("Swahili"),
    SWAZI("Swazi"),
    SWEDISH("Swedish"),
    TAMASHEK("Tamashek"),
    TAMIL("Tamil"),
    TATAR("Tatar"),
    TELUGU("Telugu"),
    THAI("Thai"),
    TIGRINYA("Tigrinya"),
    TSWA("Tswa"),
    TSWANA("Tswana"),
    TURKISH("Turkish"),
    UYGHUR("Uyghur"),
    URDU("Urdu"),
    UZBEK("Uzbek"),
    VENDA("Venda"),
    VIETNAMESE("Vietnamese"),
    WELSH("Welsh"),
    WOLOF("Wolof"),
    XHOSA("Xhosa"),
    YORUBA("Yoruba"),
    YUE("Yue"),
    ZULU("Zulu");

    public final String label;
    private static final Map<String, Language> map = new HashMap<>();

    static {
        for (Language e : values()) {
            map.put(e.label, e);
        }
    }

    Language(String label) {
        this.label = label;
    }

    public static Language valueOfName(String label) {
        return map.get(label);
    }

}

